[general]
    import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[env]
   TERM = "xterm-256color"

[window]
   startup_mode = "Maximized"

[terminal]
   shell = {program = "/usr/bin/zellij"}

[font]
   size = 13.0
